name: Flutter Android CI

on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: check java version
      run: java -version
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.24.3
    - name: check flutter version
      run: flutter --version
    - run: flutter pub get
    - run: echo $ENCODED_KEYSTORE | base64 -di > android/app/release.keystore
      env:
        ENCODED_KEYSTORE: ${{ secrets.ENCODED_KEYSTORE }}
    # 打包 APK
    - run: flutter build apk --release
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD}}
      # 发布到 Release
    - name: Release apk
      uses: ncipollo/release-action@v1.5.0
      with:
        artifacts: "build/app/outputs/apk/release/*.apk"
        token: ${{ secrets.RELEASE_TOKEN }}
